import { BackToTopButton, LoofFooter, PrimaryLink } from '../components/loof/LoofChrome'
import { Seo } from '../components/seo/Seo'

const qualityRows = [['SPECIFIC', 'People should understand exactly what they are getting.'], ['USEFUL', 'It should help someone take action.'], ['HARD TO FIND', 'The value should come from information, context, access, or connection that is not easily available elsewhere.'], ['GENUINE', 'You should actually know or have access to what you are offering.'], ['CURRENT', 'The information should still be relevant.']]
const processSteps = [['01', 'CREATE', 'You create a Lead around something useful you know.'], ['02', 'DISCOVER', 'Someone finds your Lead while looking for an answer.'], ['03', 'UNLOCK', 'They pay to access the protected information.'], ['04', 'CONNECT', 'The buyer uses the details to reach the right person or place.']]
const valueSteps = [['KNOW SOMETHING', 'Useful knowledge starts with you.'], ['CREATE A LEAD', 'Package the context, connection, or information.'], ['SOMEONE DISCOVERS IT', 'A buyer finds it when they need it.'], ['THEY UNLOCK IT', 'Protected details are revealed after payment.'], ['YOU EARN', 'The seller receives the majority of the Lead price.'], ['THEY CONNECT', 'The buyer can act on what they found.'], ['BOTH GET VALUE', 'Useful knowledge moves to the person who needs it.']]

function RoleCard({ title, subtitle, steps }: { title: string; subtitle: string; steps: string[] }) {
  return <article className="loof-role-card"><span className="loof-card-label">{title}</span><h3>{subtitle}</h3><ol>{steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong></li>)}</ol></article>
}

function HowLoofWorksPage() {
  return <main className="loof-page loof-how"><Seo description="Learn how Loof works: discover useful leads, connect with people who know what you need, and earn by sharing useful local knowledge and connections." ogDescription="Learn how Loof works: discover useful leads, connect with people who know what you need, and earn by sharing useful local knowledge and connections." title="How Loof Works — Buy and Sell Useful Knowledge" url="https://loofmarket.com/how-loof-works" /><div className="loof-how-content"><section className="loof-how-hero"><span className="loof-eyebrow">THE LOOF MARKETPLACE</span><h1>How Loof works.</h1><p className="loof-lead">Loof connects people who know something useful with people who need it.</p><p>Discover useful local knowledge, trusted connections, recommendations, and hard-to-find information.</p></section>
    <div className="loof-how-sections">
      <section className="loof-how-section"><h2>What is a Lead?</h2><p>A Lead is a piece of useful information that helps someone solve a real problem.</p><ul className="loof-bullet-list"><li>It can be a person, place, recommendation, connection, or hard-to-find detail.</li><li>The seller decides what to share publicly and what to protect.</li><li>The buyer pays to unlock the information that helps them move forward.</li></ul><article className="loof-lead-preview-card"><span className="loof-card-label">PUBLIC DETAILS</span><h3>Reliable electrician in Kochi</h3><p>Handles emergency repairs. Trusted by local word of mouth.</p><div className="loof-card-meta">1 Contact · 1 WhatsApp · 1 Location</div><div className="loof-protected-preview"><span>PROTECTED INFORMATION</span><strong>Unlock to view contact details</strong></div></article></section>
      <section className="loof-how-section"><h2>Every Lead has two sides.</h2><div className="loof-role-grid"><RoleCard title="THE SELLER" subtitle="Someone who knows something useful." steps={['Create a Lead', 'Set the price', 'Receive the unlock payment']} /><RoleCard title="THE BUYER" subtitle="Someone who needs that information." steps={['Discover a Lead', 'Unlock the protected information', 'Connect with the seller']} /></div><p className="loof-centered-note">A person can be both a buyer and a seller on Loof.</p></section>
      <section className="loof-how-section"><h2>From something you know to something useful.</h2><div className="loof-process-grid">{processSteps.map(([number, title, body]) => <article className="loof-process-step" key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="loof-how-section"><h2>Some value is better kept private.</h2><p>A Lead can tell buyers what they are getting without giving away the information they actually need.</p><div className="loof-public-protected-grid"><article className="loof-information-card"><span className="loof-card-label">PUBLIC DETAILS</span><h3>Reliable electrician in Kochi</h3><p>Handles emergency repairs</p><p>Trusted by local word of mouth</p><div className="loof-card-meta">1 Contact · 1 WhatsApp · 1 Location</div></article><article className="loof-information-card loof-protected-card"><span className="loof-card-label">LOCKED DATA (HIDDEN)</span><div className="loof-protected-tags"><span>Contact number</span><span>WhatsApp</span><span>Location</span></div></article></div><p className="loof-callout">Protected information is only revealed after the buyer has successfully unlocked the Lead.</p></section>
      <section className="loof-how-section"><h2>You choose what your knowledge is worth.</h2><p>The seller sets the price for each Lead. Loof keeps a platform fee and the seller earns the rest.</p><article className="loof-pricing-card"><span className="loof-card-label">ILLUSTRATIVE EXAMPLE</span><div className="loof-pricing-row"><span>LEAD PRICE</span><strong>₹100</strong></div><div className="loof-pricing-row is-highlight"><span>SELLER EARNINGS</span><strong>₹80</strong></div><div className="loof-pricing-row"><span>PLATFORM FEE</span><strong>₹20</strong></div><small>This is an illustrative example. Actual pricing and fees may vary.</small></article></section>
      <section className="loof-how-section"><h2>Good Leads solve real problems.</h2><p>People should understand why a Lead is useful before they decide to unlock it.</p><div className="loof-quality-table">{qualityRows.map(([label, body]) => <div className="loof-quality-row" key={label}><strong>{label}</strong><span>{body}</span></div>)}</div><blockquote className="loof-quality-quote">“Don’t sell what anyone can find in a quick search.<br />Sell the context, connection, experience, or information that makes the search easier.”</blockquote></section>
      <section className="loof-how-section"><h2>Useful information builds trust.</h2><p>As people create and unlock useful Leads, the marketplace gets better for everyone.</p><div className="loof-trust-tags"><span>TRANSACTIONS</span><span>RATINGS</span><span>REVIEWS</span><span>USEFUL LEADS</span><span className="is-active">REPUTATION</span></div></section>
      <section className="loof-value-section"><span className="loof-eyebrow">A SIMPLE EXCHANGE</span><h2>Know something useful?</h2><p>Someone else might need it.</p><div className="loof-vertical-flow">{valueSteps.map(([title, body]) => <div className="loof-value-step" key={title}><strong>{title}</strong><span>{body}</span></div>)}</div></section>
      <section className="loof-final-cta"><h2>Ready to explore Loof?</h2><p>Find something useful — or share something you know.</p><PrimaryLink to="/">Back to home →</PrimaryLink></section>
    </div></div><LoofFooter /><BackToTopButton /></main>
}

export default HowLoofWorksPage
